### ISSUE TITLE
OpenSprinkler: rs has been replaced by sn1 in firmware 2.1.9

### ISSUE THREAD

**Issue by rudybrian** [hplato/misterhouse#27]
https://github.com/hplato/misterhouse/blob/2cdf5e9c9eaecc6e5966c996fb1c924b1123ea36/lib/OpenSprinkler.pm#L219

Per https://opensprinkler.com/forums/topic/open-sprinkler-api/ 'rs' is is no longer present in the API for firmware 2.1.9 and has been replaced by 'sn1'.

I made the following tweak for my OS 2.3 hardware running 2.1.9 (7) and it seems to work:

```
        if (exists($vars->{rs})) {
            $self->{data}->{info}->{rain_sensor_status} = ( $vars->{rs} == 0 ) ? "off" : "on";
        }
        else {
            # rs has been replaced by sn1 for firmware 2.1.9 and up
            $self->{data}->{info}->{rain_sensor_status} = ( $vars->{sn1} == 0 ) ? "off" : "on";
        }
```

**Comment by hplato** [comment]
Thanks Brian!

**Comment by hplato** [comment]
Updated!
